services:

  eldes-app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: ${CONTAINER_REGISTRY}/eldes-app:${TAG}
    container_name: eldes-app
    restart: always
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8122:80"
    environment:
      - BUILD_NUMBER=${TAG}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gate.rule=Host(`gate.housekpr.ru`)"
    networks:
      - housekpr-network

networks:
  housekpr-network:
    external: true